# Generated by Django 5.1 on 2024-08-28 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.CharField(max_length=50)),
                ('Document', models.CharField(max_length=50)),
                ('Transfer', models.CharField(max_length=50)),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TransmissionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TyreCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Color', models.CharField(max_length=50)),
                ('Mileage', models.CharField(max_length=50)),
                ('BHP', models.IntegerField()),
                ('Torque', models.IntegerField()),
                ('CC', models.IntegerField()),
                ('CO2', models.IntegerField()),
                ('Year', models.IntegerField()),
                ('Insurance', models.CharField(max_length=100)),
                ('About', models.CharField(max_length=500)),
                ('BodyType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.body')),
                ('Fuel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.fueltype')),
                ('Make', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.make')),
            ],
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_images/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.car')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('make', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.make')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='Model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.model'),
        ),
        migrations.CreateModel(
            name='CarSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Registration', models.CharField(max_length=50)),
                ('Year', models.IntegerField()),
                ('Mileage', models.IntegerField()),
                ('Color', models.CharField(max_length=50)),
                ('ServiceHistory', models.CharField(max_length=255)),
                ('ServiceBookPresent', models.CharField(max_length=255)),
                ('LastServiceDate', models.DateField()),
                ('LastServiceMileage', models.IntegerField()),
                ('NumberOfKeys', models.IntegerField()),
                ('IsTheCarModified', models.BooleanField()),
                ('TyreBrand', models.CharField(max_length=100)),
                ('TyreCondition', models.CharField(max_length=100)),
                ('ConditionDamageReport', models.CharField(max_length=255)),
                ('OutstandingFinance', models.CharField(max_length=100)),
                ('DesiredValue', models.IntegerField()),
                ('Car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CarSubmission', to='main.car')),
                ('FuelType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.fueltype')),
                ('Transmission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.transmissiontype')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='Transmission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.transmissiontype'),
        ),
    ]
