# Generated by Django 5.1 on 2024-08-21 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Make', models.CharField(max_length=50)),
                ('Model', models.CharField(max_length=50)),
                ('Category', models.CharField(choices=[('Sedan', 'Sedan'), ('Coupe', 'Coupe'), ('Sportscars', 'Sportscars'), ('Station wagon', 'Station wagon'), ('Hatchback', 'Hatchback'), ('Convertible', 'Convertible'), ('SUV', 'Sport-utility vehicle (SUV)'), ('Minivan', 'Minivan'), ('Pickup truck', 'Pickup truck'), ('Jeep', 'Jeep'), ('Electric car', 'Electric car'), ('CUV', 'CUV/Crossover'), ('Spyder', 'Spyder'), ('Hot hatch', 'Hot hatch'), ('Limousine', 'Limousine'), ('UTE', 'UTE'), ('Pony car', 'Pony car'), ('Sports sedan', 'Sports sedan'), ('Military vehicle', 'Military vehicle'), ('Dragster', 'Dragster')], max_length=50)),
                ('Name', models.CharField(max_length=100)),
                ('Transmission', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic'), ('Semi-Automatic', 'Semi-Automatic'), ('CVT', 'CVT (Continuously Variable Transmission)'), ('Dual-Clutch', 'Dual-Clutch'), ('Tiptronic', 'Tiptronic'), ('DSG', 'DSG (Direct-Shift Gearbox)'), ('AMT', 'AMT (Automated Manual Transmission)'), ('4-Speed Automatic', '4-Speed Automatic'), ('5-Speed Automatic', '5-Speed Automatic'), ('6-Speed Automatic', '6-Speed Automatic'), ('7-Speed Automatic', '7-Speed Automatic'), ('8-Speed Automatic', '8-Speed Automatic'), ('9-Speed Automatic', '9-Speed Automatic'), ('10-Speed Automatic', '10-Speed Automatic'), ('5-Speed Manual', '5-Speed Manual'), ('6-Speed Manual', '6-Speed Manual'), ('7-Speed Manual', '7-Speed Manual'), ('8-Speed Manual', '8-Speed Manual'), ('Electric Single-Speed', 'Electric Single-Speed')], default='Metallic', max_length=50)),
                ('Color', models.CharField(max_length=50)),
                ('Mileage', models.CharField(max_length=50)),
                ('Fuel', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Biodiesel', 'Biodiesel'), ('Electric', 'Electric')], max_length=50)),
                ('BHP', models.IntegerField()),
                ('Torque', models.IntegerField()),
                ('CC', models.IntegerField()),
                ('CO2', models.IntegerField()),
                ('Year', models.IntegerField()),
                ('Insurance', models.CharField(max_length=100)),
                ('About', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Make', models.CharField(max_length=100)),
                ('Model', models.CharField(max_length=100)),
                ('Registration', models.CharField(max_length=50)),
                ('Year', models.IntegerField()),
                ('Mileage', models.IntegerField()),
                ('Color', models.CharField(max_length=50)),
                ('FuelType', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Biodiesel', 'Biodiesel'), ('Electric', 'Electric')], max_length=50)),
                ('Transmission', models.CharField(choices=[('Metallic', 'Metallic'), ('Pearlescent', 'Pearlescent'), ('Matte', 'Matte'), ('Glossy', 'Glossy'), ('Solid', 'Solid'), ('Two-tone', 'Two-tone'), ('Chrome', 'Chrome'), ('Carbon Fiber', 'Carbon Fiber'), ('Vinyl Wrap', 'Vinyl Wrap'), ('Custom Paint', 'Custom Paint'), ('Convertible Top', 'Convertible Top'), ('Soft Top', 'Soft Top'), ('Hard Top', 'Hard Top'), ('Sunroof', 'Sunroof'), ('Panoramic Sunroof', 'Panoramic Sunroof'), ('Targa Top', 'Targa Top'), ('Widebody Kit', 'Widebody Kit'), ('Off-road Kit', 'Off-road Kit'), ('Racing Livery', 'Racing Livery')], default='Metallic', max_length=50)),
                ('ServiceHistory', models.CharField(max_length=255)),
                ('ServiceBookPresent', models.CharField(max_length=255)),
                ('LastServiceDate', models.DateField()),
                ('LastServiceMileage', models.IntegerField()),
                ('NumberOfKeys', models.IntegerField()),
                ('IsTheCarModified', models.BooleanField()),
                ('TyreBrand', models.CharField(max_length=100)),
                ('TyreCondition', models.CharField(max_length=100)),
                ('ConditionDamageReport', models.CharField(max_length=255)),
                ('OutstandingFinance', models.CharField(max_length=100)),
                ('DesiredValue', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_images/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.car')),
            ],
        ),
    ]
