# Generated by Django 5.1 on 2024-08-28 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carsubmission',
            name='Car',
        ),
        migrations.AddField(
            model_name='carsubmission',
            name='Make',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.make'),
        ),
        migrations.AddField(
            model_name='carsubmission',
            name='Model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.model'),
        ),
    ]
