# Generated by Django 5.1 on 2024-08-21 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicledetails',
            name='Make',
        ),
        migrations.RemoveField(
            model_name='vehicledetails',
            name='Model',
        ),
        migrations.AddField(
            model_name='vehicledetails',
            name='Car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='CarInfo', to='main.car'),
            preserve_default=False,
        ),
    ]
