# Generated by Django 5.1 on 2024-08-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_carsubmission_car_carsubmission_make_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('PhoneNumber', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=40)),
                ('Message', models.CharField(max_length=1000)),
            ],
        ),
    ]
