# Generated by Django 5.1 on 2024-08-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_vehicledetails_make_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.CharField(max_length=50)),
                ('Document', models.CharField(max_length=50)),
                ('Transfer', models.CharField(max_length=50)),
            ],
        ),
    ]
