# Generated by Django 5.1 on 2024-08-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_callback'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsubmission',
            name='MakeName',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carsubmission',
            name='ModelName',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
