# Generated by Django 5.1 on 2024-08-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_carsubmission_makename_carsubmission_modelname'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='Price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='make',
            name='logo',
            field=models.ImageField(default=1, upload_to='car_logos/'),
            preserve_default=False,
        ),
    ]
