# Generated by Django 5.1 on 2024-08-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_plates_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='car_photos/'),
        ),
    ]
