# Generated by Django 5.1 on 2024-08-29 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_car_price_make_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarSubmissionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_sub_images/')),
                ('car_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='main.carsubmission')),
            ],
        ),
    ]
