# Generated by Django 5.1 on 2024-08-23 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_car_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='Photo',
        ),
    ]
