# Generated by Django 5.1 on 2024-08-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_color_alter_car_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='TyreBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
