# Generated by Django 5.1 on 2024-09-02 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_carsubmission_makename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsubmissionphoto',
            name='car_sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_photos', to='main.carsubmission'),
        ),
        migrations.CreateModel(
            name='CarPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_photos/')),
                ('car_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='main.carsubmission')),
            ],
        ),
    ]
