# Generated by Django 5.1 on 2024-09-02 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_carsubmissionphoto_car_sub_carphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='callback',
            name='SubId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.carsubmission'),
        ),
    ]
