# Generated by Django 5.1 on 2024-09-09 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_callback_subid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OptionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='Options',
            field=models.ManyToManyField(blank=True, related_name='cars', to='main.caroption'),
        ),
        migrations.AddField(
            model_name='caroption',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='main.optioncategory'),
        ),
    ]
