# Generated by Django 5.1 on 2024-12-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_homepage_alter_car_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='BHP',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='CC',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='CO2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='Price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='Torque',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='Year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carsubmission',
            name='ConditionDamageReport',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='carsubmission',
            name='DesiredValue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carsubmission',
            name='IsTheCarModified',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carsubmission',
            name='LastServiceDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carsubmission',
            name='LastServiceMileage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carsubmission',
            name='NumberOfKeys',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carsubmission',
            name='OutstandingFinance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='carsubmission',
            name='Registration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='carsubmission',
            name='ServiceBookPresent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='carsubmission',
            name='ServiceHistory',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='carsubmission',
            name='TyreBrand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='carsubmission',
            name='TyreCondition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
